version: '3.8'

services:
  vault:
    image: vault:1.10.1
    cap_add:
      - IPC_LOCK
    ports:
      - 8082:8200

  netbox:
    image: netboxcommunity/netbox:v3.2.1
    ports:
      - 8081:8080
    depends_on:
      - postgres
      - redis
    command:
      - /opt/netbox/plugin-entrypoint.sh
      - /opt/netbox/launch-netbox.sh
    volumes:
      - ./:/src
      - ./devel/plugins.py:/etc/netbox/config/plugins.py
      - ./devel/entrypoint.sh:/opt/netbox/plugin-entrypoint.sh
    environment:
      NETBOX_VAULT_DEVELOP: "True"
      CORS_ORIGIN_ALLOW_ALL: "True"
      DB_HOST: postgres
      DB_NAME: netbox
      DB_PASSWORD: J5brHrAXFLQSif0K
      DB_USER: netbox
      REDIS_CACHE_DATABASE: "1"
      REDIS_CACHE_HOST: redis-cache
      REDIS_CACHE_PASSWORD: ieGhaez1aihah1
      REDIS_CACHE_SSL: "false"
      REDIS_DATABASE: "0"
      REDIS_HOST: redis
      REDIS_PASSWORD: H733Kdjndks81
      REDIS_SSL: "false"
      SECRET_KEY: r8OwDznj!!dci#P9ghmRfdu1Ysxm0AiPeDCQhKE+N_rClfWNj
      SKIP_SUPERUSER: "false"
      SUPERUSER_API_TOKEN: 0123456789abcdef0123456789abcdef01234567
      SUPERUSER_EMAIL: admin@example.com
      SUPERUSER_NAME: admin
      SUPERUSER_PASSWORD: admin
    healthcheck:
      test: curl -f http://localhost:8080
  postgres:
    image: postgres:15-alpine
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: netbox
      POSTGRES_PASSWORD: J5brHrAXFLQSif0K
      POSTGRES_USER: netbox
    healthcheck:
      test: pg_isready
  redis:
    &redis
    image: redis:6-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    volumes:
      - netbox-redis-data:/data
    environment:
      REDIS_PASSWORD: H733Kdjndks81
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
  redis-cache:
    <<: *redis
    environment:
      REDIS_PASSWORD: ieGhaez1aihah1

volumes:
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
